### ISSUE TITLE
Сверстать главную страницу

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#1]
- [x] Главное меню сверху #37
- [x] Логотип #38
- [x] Врезка о конференции #39
- [x] Врезка о подкасте #40
- [x] Свежие статьи #41
  - [x] Название статьи
  - [x] Имя автора
  - [x] Дата публикации
  - [x] Текст анонса
- [x] Ссылка на все статьи #42
- [x] Ссылки на социальные сети в подвале #43
- [x] Футер #44

----
![Index](https://user-images.githubusercontent.com/2804205/62806733-56112580-bafc-11e9-9a2f-42b008a9b87e.png)

**Comment by higimo** [comment]
@pepelsbey это пример задачи (но настоящей). Давай обсудим, норм ли такое или лучше дробить ещё меньше? Если дробить, то я создам «подзадачи» и укажу ссылку здесь через решётку. Так видно будет, что из страницы ещё не сделано, но при этом сходить и забрать себе отдельную задачу.

Давай договоримся про способ «смешивания» данных в одном макете? Главное меню будет на каждой странице, а блок с новыми статьями тоже хотелось бы иметь где-то снаружи (проще следить за обновлением отдельного файла в коммите). Вроде как [Элевенти умеет в такое](https://www.11ty.io/docs/data/).

Дальше хотелось бы выяснить детали дизайна, с которыми рано или поздно столкнуться все.

Можешь ещё пояснить, к чему относится картинка с фехтовальщиками?

Почему нет аватарки у Константинопольского?

Это умышленное решение, что здесь нет видосов с конференций? Умышленно ли нет ссылки на конференцию во врезке сверху?

Правильно понимаю, что люди (и аватарки) не кликабельны?

Что здесь кликабельно? Как ховерится статья, элемент главного меню и кнопка социалки? Сможет ли это додизайнить Штанг или как-то сами решим?

**Comment by pepelsbey** [comment]
> норм ли такое или лучше дробить ещё меньше?

Кажется, что норм.

> Давай договоримся про способ «смешивания» данных

Не уверен, что понял, о чём речь.

> К чему относится картинка с фехтовальщиками?

Это иллюстрация к статье про доступные SVG-иконки

> Это умышленное решение, что здесь нет видосов с конференций?

Первый майлстоун — запустить только сайт со статьями, дальше будем продолжать интегрировать весь остальной контент.

> Правильно понимаю, что люди (и аватарки) не кликабельны?

На этой итерации — да, я предлагаю тизеры статей сделать большими ссылками, которые ведут внутрь.

> Что здесь кликабельно? Как ховерится

Это либо решаем сами, либо не делаем и спрашиваем у дизайнера.
