### ISSUE TITLE
Сверстать карточку статьи

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#3]
- [x] Карточка статьи. Блок авторов и соавторов #53
- [x] Карточка статьи. Текст статьи #54
- [x] Карточка статьи. Статьи по теме #55
- [x] Карточка статьи. Ссылка на конференцию #56
- [x] Карточка статьи. Прикрипить вёрстку футера #57

----

![Article](https://user-images.githubusercontent.com/2804205/62827097-50394400-bbd1-11e9-9cea-198814ed5dc4.png)

**Comment by PsarewIvan** [comment]
@vsesvitlo, задачами #52, #53 я сейчас занимаюсь тут: https://github.com/web-standards-ru/nouvelle/pull/76

**Comment by vsesvitlo** [comment]
> @vsesvitlo, задачами #52, #53 я сейчас занимаюсь тут: #76

Ок, на этих задачах мне снять пометку assign с себя?

**Comment by PsarewIvan** [comment]
Да, снимите пожалуйста

**Comment by vsesvitlo** [comment]
> Да, снимите пожалуйста

Готово
